-- MySQL Script generated by MySQL Workbench
-- Sun May 10 12:27:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lisdbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lisdbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lisdbd` DEFAULT CHARACTER SET utf8 ;
USE `lisdbd` ;

-- -----------------------------------------------------
-- Table `lisdbd`.`Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lisdbd`.`Option` (
  `idOption` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` TINYINT NULL,
  PRIMARY KEY (`idOption`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lisdbd`.`Situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lisdbd`.`Situacao` (
  `idSituation` INT NOT NULL,
  `imagem` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idSituation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lisdbd`.`Option_has_Situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lisdbd`.`Option_has_Situacao` (
  `Option_idOption` INT NOT NULL,
  `Situacao_idSituation` INT NOT NULL,
  PRIMARY KEY (`Option_idOption`, `Situacao_idSituation`),
  INDEX `fk_Option_has_Situacao_Situacao1_idx` (`Situacao_idSituation` ASC) VISIBLE,
  INDEX `fk_Option_has_Situacao_Option1_idx` (`Option_idOption` ASC) VISIBLE,
  CONSTRAINT `fk_Option_has_Situacao_Option1`
    FOREIGN KEY (`Option_idOption`)
    REFERENCES `lisdbd`.`Option` (`idOption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Option_has_Situacao_Situacao1`
    FOREIGN KEY (`Situacao_idSituation`)
    REFERENCES `lisdbd`.`Situacao` (`idSituation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
